# Site settings
title: Notebook
email: datafig@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  Bits of information - Note to "Self"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://datafig.github.io" # the base hostname & protocol for your site
twitter_username: datafig
github_username:  datafig
permalink: pretty

# Build settings
markdown: kramdown
